version: '3.8'

services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.yml:/app/config/application.yml  # 挂载 YAML 配置文件

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql      # 本地目录挂载
      - ./db:/docker-entrypoint-initdb.d  # 初始化脚本挂载
